### ISSUE TITLE
Project not working

### ISSUE THREAD

**Issue by garak** [skornev/vichbundle-sandbox-not-cp-symfony3.3#1]
Cloned repo, ran `composer install` and got this:
```
 [RuntimeException]                                                                                     
  Could not scan for classes inside "app/AppKernel.php" which does not appear to be a file nor a folder 
```

**Comment by skornev** [comment]
Actually I thought it would be used in  a fresh symfony copy and then just overwritten by the project files. 
That's why I did not include AppKernel and AppCache. 
I will fix that issue on Monday to make it work without installing symfony  first.

If you have time you can just
1) install a fresh symonfy 3.3
2) overwrite by the files from the repo
3) composer update
4) Add vich bundle to AppKernel

**Comment by skornev** [comment]
Fixed. Please, try again.
